### ISSUE TITLE
Glow Type Element is not assignable to type undefined

### ISSUE THREAD

**Issue by glpecile** [codaworks/react-glow#2]
Typings might have something wrong as children are defined as undefined causing "TS2322: Type Element is not assignable to type undefined" when passing any element as children to the Glow component.

**Comment by mordechaim** [comment]
Thanks for the report, I'm not very well versed with typescript.

Will fix soon

**Comment by glpecile** [comment]
No worries, for now as a quick fix so that typescript doesn't shout at me I made it so that my component I'm using as children is defined set `as unknown as undefined` but it would be ideal if the types were better defined.

**Comment by Varkoff** [comment]
Hi, got the same issue! Went to the `node_modules/@codaworks/react-glow/dist/index.d.ts` file to directly edit the type for children to React.ReactNode.

Wrong fix I know, but the error is gone ! 

Also got a type issue, importing the tailwind config plugin in a .ts file. (using import annotation)

**Comment by BijesniPatuljak** [comment]
I did mostly the same as @Varkoff but I set the children attribute to be of type `React.JSX.Element | undefined`
