### ISSUE TITLE
Does not work properly with forms

### ISSUE THREAD

**Issue by andreialecu** [codaworks/react-glow#5]
Because this code naively duplicates the elements:

https://github.com/codaworks/react-glow/blob/bb2fb16fa26e7776c162ab272ac4eb2e91b0a35a/src/index.tsx#L110

It creates issues when using `<input>` or `<form ref={...}`. 

Issues I noticed: 
- the `ref` gets updated to the cloned element's ref and hence is disconnected from inputs
- if I move the form above `<Glow>` that helps, however, now there are duplicated inputs inside the form, and if the cloned ones have `required` on them for example, they will fail validation.

**Comment by mordechaim** [comment]
The cloning of the children is required for the effect to properly work. In your case you could likely use a callback ref and check if the ref object is already set before assigning.

I will add an explainer to the readme and list all the limitations and implications of this behavior.

**Comment by andreialecu** [comment]
Perhaps instead of rendering children twice directly, a solution like the following might work:

```ts
React.cloneElement(child, { ref: null })
```

It would need to be done recursively via something like:

https://stackoverflow.com/a/57993188

**Comment by andreialecu** [comment]
One other quirk with forms was that the placeholder text, or previous text in the inputs would "ghost" over when hovering.

I worked around this with `glow:text-transparent` on the input/select elements.
