### ISSUE TITLE
Firefox Issue

### ISSUE THREAD

**Issue by dustgg** [codaworks/react-glow#7]
The hover effect seems to just be shown all the time in Firefox 131.0.3

Firefox:
https://github.com/user-attachments/assets/cd581740-7faf-4b5b-8cfe-bcdccb12f05c

Brave:
https://github.com/user-attachments/assets/943e600a-8f77-4a8c-ad32-00d1b154c7f2

**Comment by dustgg** [comment]
Following up - I see on your website it works in Firefox. Likely an implementation problem on my end. It's within a react app fwiw, let me know if I can provide any more details!

**Comment by dustgg** [comment]
Closing the issue - seems to be something to do with using background blur filters. When I remove that, it works in Firefox.

**Comment by dustgg** [comment]
Closing the issue - seems to be something to do with using background blur filters. When I remove that, it works in Firefox.

**Comment by mordechaim** [comment]
I'm glad you fixed it. You can debug issues I'm using the `debug` prop on `<Glow>`, which removes the css mask.

It might be backdrop filters don't work nicely with masks 🤷
